### ISSUE TITLE
download the data

### ISSUE THREAD

**Issue by Aidenfaustine** [lstappen/MuSe2021#1]
Dear professors:

I am sorry to disturb you. I read the readme about downloading the dataset.

I want to knon where I can download  the dataset?

Thanks

![image](https://user-images.githubusercontent.com/82608348/120676835-58d9c900-c48e-11eb-9264-d5f7044f1a33.png)

**Comment by aliceebaird** [comment]
> Dear professors:
> 
> I am sorry to disturb you. I read the readme about downloading the dataset.
> 
> I want to knon where I can download the dataset?
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/82608348/120676835-58d9c900-c48e-11eb-9264-d5f7044f1a33.png)

Hi @Aidenfaustine 

Thanks for your interest in the challenge! 

After submitting the EULA which you can find on the [MuSe webpage](https://www.muse-challenge.org/) - You can download the datasets from Zenodo:

MuSe-CaR (raw, no labels): https://zenodo.org/record/4651164 (32 GB)
Task-specific features and labels (each around 12 GB) 
MuSe-Wilder: https://zenodo.org/record/4652376
MuSe-Sent: https://zenodo.org/record/4654371

Ulm-TSST (raw, no labels): https://doi.org/10.5281/zenodo.4767117 (32 GB)
MuSe-Stress: https://doi.org/10.5281/zenodo.4767114
MuSe-Physio: https://doi.org/10.5281/zenodo.4765992
