### ISSUE TITLE
target can not be optimized for 15 consecutive epochs, early stop the training process!

### ISSUE THREAD

**Issue by Aidenfaustine** [lstappen/MuSe2021#3]
When I run the command line: python main.py --task wilder --emo_dim arousal --feature_set egemaps --normalize --norm_opts y --d_rnn 128 --rnn_n_layers 4 --epochs 50 --batch_size 256 --n_seeds 10 --win_len 300 --hop_len 200 --use_gpu --cache --save --save_path preds

Due to my device, I try to reduce the size of batchsize from 1024 to 256. However, the target can not be optimized for 15 consecutive epochs, early stop the training process!
![image](https://user-images.githubusercontent.com/82608348/122051347-68390a80-cddc-11eb-960a-8de8ec86e66d.png)

How to fix this issues? Could you please give me more detailed guidance? I lack the background of CS/EE. 
Thanks
Best wishes.

**Comment by lc0197** [comment]
[Early Stopping](https://machinelearningmastery.com/early-stopping-to-avoid-overtraining-neural-network-models/) is intended and not an issue.
