### ISSUE TITLE
Problem with replicating baseline results

### ISSUE THREAD

**Issue by Harsha-madyastha** [lstappen/MuSe2021#4]
hello,
I tried to run the baseline code using the command given on Github and also using the parameters given in the paper. But both of the codes aren't replicating the results given. I also tried to use the model given in the reproducibility column but couldn't solve the compatibility issue. I have also attached the screenshot of the obtained results for both the above scenarios respectively. 
(I am using the CPU version,
Github- main.py --task stress --emo_dim arousal --feature_set egemaps --d_rnn 64 --rnn_n_layers 4 --rnn_bi --lr 0.002 --epochs 100 --batch_size 1024 --n_seeds 10 --win_len 300 --hop_len 50 --cache --save --save_path preds --predict

paper- main.py --task stress --emo_dim arousal --feature_set egemaps --d_rnn 64 --rnn_n_layers 4 --lr 0.0002 --epochs 100 --batch_size 1024 --n_seeds 10 --win_len 300 --hop_len 50 --cache --save --save_path preds --predict)

Could you please let me know what can be done differently to get the results given in the paper?

![lr_rate_0 002](https://user-images.githubusercontent.com/63476063/129424356-b47fd01b-6364-4862-b8e7-b2889938b65c.png)
![lr_rate_0 02](https://user-images.githubusercontent.com/63476063/129424369-92eaf840-765a-4267-ac0c-93c79a3b8f73.png)

**Comment by lc0197** [comment]
Hi,
the main problem is probably that you do not normalize the egemaps features. This is crucial for this feature set. To do normalization, simply add the flag ``--normalize y`` to your calls.

**Comment by Harsha-madyastha** [comment]
Hello,
Thank you for the reply and it did show results as mentioned in the baseline.
I just wanted to bring to your notice about some irregularities in the data which I found while working. 
1. In the given vggface features set, files 38,62,65 and 73rd have the feature column from 1-512, whereas for others it is 0-511.
2. There are some missing raw images in some of the files, where the number of images does not match the number of output variables.
